# Example ESPHome configuration for HubSpace Fan/Light
esphome:
  name: hubspace-fan-light

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  - platform: esphome

# WiFi configuration
wifi:
  ssid: "YourSSID"
  password: "YourPassword"

# UART configuration (9600 8N1)
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# HubSpace component
hubspace:
  id: hubspace_hub

# Fan configuration
fan:
  - platform: hubspace
    name: "HubSpace Fan"
    hubspace_id: hubspace_hub

# Light configuration
light:
  - platform: hubspace
    name: "HubSpace Light"
    hubspace_id: hubspace_hub
